# Используем образ с PostgreSQL 15
FROM postgres:15.0-alpine

# Копируем init.sql внутрь контейнера
COPY init.sql /docker-entrypoint-initdb.d/

# Устанавливаем переменные окружения для PostgreSQL
ENV POSTGRES_HOST_AUTH_METHOD trust