# Используем образ с PostgreSQL 15
FROM postgres:15

# Копируем init.sql внутрь контейнера
COPY init.sql /docker-entrypoint-initdb.d/

# Устанавливаем переменные окружения для PostgreSQL
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword