version: '3.3'

services:
  web:
    image: rails_test_app_dz1:latest
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres@postgres42/somedatabase_production
      - RAILS_LOG_TO_STDOUT=1


  postgres42:
    image: postgres:14.6-alpine
    volumes:
      - postgres_vol:/var/lib/postgresql/data:cached
      - ./dumps/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGPORT= 5435      

volumes:
  postgres_vol:
