version: '3'
services:
  # Сервис с PostgreSQL
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    ports:
      - "5433:5432" # Маппинг портов, если нужно обращаться к базе с хоста
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER_NAME}
      POSTGRES_PASSWORD: ${PG_USER_PASSWORD}
    env_file:
      - .env      

  # Сервис с Rails приложением
  web:
    build:
      context: .
      dockerfile: Dockerfile.rails
    ports:
      - "3000:3000" # Маппинг портов, если нужно обращаться к приложению с хоста
    depends_on:
      - db # Указываем, что зависим от сервиса с PostgreSQL
    volumes:
      - .:/app # Монтируем текущую директорию внутрь контейнера
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
    env_file:
      - .env
      
volumes:
  db-data: # Volume для данных PostgreSQL